// <auto-generated />
using System;
using Bai02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bai02.Migrations
{
    [DbContext(typeof(Bai02aContext))]
    [Migration("20260128031215_InitDb_A")]
    partial class InitDb_A
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bai02.Models.NhanVienA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoNv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Luong")
                        .HasColumnType("float");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("Bai02.Models.ThanNhanA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NhanVienAId")
                        .HasColumnType("int");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienAId");

                    b.ToTable("ThanNhans");
                });

            modelBuilder.Entity("Bai02.Models.ThanNhanA", b =>
                {
                    b.HasOne("Bai02.Models.NhanVienA", "NhanVienA")
                        .WithMany("ThanNhans")
                        .HasForeignKey("NhanVienAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVienA");
                });

            modelBuilder.Entity("Bai02.Models.NhanVienA", b =>
                {
                    b.Navigation("ThanNhans");
                });
#pragma warning restore 612, 618
        }
    }
}
