// <auto-generated />
using System;
using Bai02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bai02.Migrations.Bai02b
{
    [DbContext(typeof(Bai02bContext))]
    partial class Bai02bContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bai02.Models.NhanVienB", b =>
                {
                    b.Property<string>("MaNv")
                        .HasColumnType("char(9)")
                        .HasColumnName("MANV");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nchar(30)")
                        .HasColumnName("DCHI");

                    b.Property<string>("HoNv")
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("HONV");

                    b.Property<double?>("Luong")
                        .HasColumnType("float")
                        .HasColumnName("LUONG");

                    b.Property<string>("MaNql")
                        .HasColumnType("char(9)")
                        .HasColumnName("MA_NQL");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Phai")
                        .HasColumnType("nchar(3)")
                        .HasColumnName("PHAI");

                    b.Property<int?>("Phg")
                        .HasColumnType("int")
                        .HasColumnName("PHG");

                    b.Property<string>("TenLot")
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TENLOT");

                    b.Property<string>("TenNv")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TENNV");

                    b.HasKey("MaNv");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("Bai02.Models.ThanNhanB", b =>
                {
                    b.Property<string>("MaNvien")
                        .HasColumnType("char(9)")
                        .HasColumnName("MA_NVIEN");

                    b.Property<string>("TenTn")
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TENTN");

                    b.Property<DateTime?>("NgSinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGSINH");

                    b.Property<string>("Phai")
                        .HasColumnType("nchar(3)")
                        .HasColumnName("PHAI");

                    b.Property<string>("QuanHe")
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("QUANHE");

                    b.HasKey("MaNvien", "TenTn");

                    b.ToTable("THANNHAN");
                });

            modelBuilder.Entity("Bai02.Models.ThanNhanB", b =>
                {
                    b.HasOne("Bai02.Models.NhanVienB", "NhanVien")
                        .WithMany("ThanNhans")
                        .HasForeignKey("MaNvien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Bai02.Models.NhanVienB", b =>
                {
                    b.Navigation("ThanNhans");
                });
#pragma warning restore 612, 618
        }
    }
}
